### ISSUE TITLE
Events Page - Filter Button Component

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#103]
The filter button will collect all data that share the same attribute to filter. This filter button should be focus on time filter in which we will use it in events page to render event widgets by year. Filter buttons will be rendered in a row above the pagination. 

From left to right, buttons list will be 2022 2021 2020 2019 2018 Older. Here are the logic for revealing filter buttons:
- Because, this project is new there won't be any events in years that older than the current year. It should only show 2022. 
- If there are more than 1 and lest than 5 years in the past, those buttons of those past years are revealed. 
- If older than 5 years, Older will be revealed. When the user click on Older button, it will reveal all older year buttons on the same line.

Use `tailwind css` for styling. Button should be round rectangle. 
Color is up to the programmer who is in charge for this task. 
If using orange color, please use `#ff9617`

**Comment by amrittimalsina** [comment]
Can you assign this to me? I would love to work on this!

**Comment by minhngo3818** [comment]
Before you start, please create your branch from `minhngo-events-optimize-cleanup` branch, then name it as 
`<your-github-name or issue-number>-event-year-filter`. I have just moved all components of event page to directory `client/components/events`. 

Add your code file in the directory.

If you have any question, please let know.

**Comment by minhngo3818** [comment]
This issue is outdated. A new issue will be created to describe the task that corresponds to the new design
