### ISSUE TITLE
Frontend -Title

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#128]
Title component is placed at the top and indicates the name of the page or a section of a page. Use ```Tailwind``` to implement this component. For beginners, you can play around with CSS before implementing tailwind. Before and after elements can be tricky. Feel free to reach out if having any difficulties.

Directory: ../client/src/components/title/title.jsx
Component name: Title
Props: 
- ```color```, type string: name of the color (orange, blue)
- ```title```, type string: name of the page or section
Tailwind doc: https://tailwindcss.com/docs/aspect-ratio

Styling details:
- width: depend on the parent component
- height: 72px
- display: flex,
- justify: center
- items (align items): center
- line and brace color: #ff9617 (orange) or #2196f3 (blue)
- title font size: 40px ( or text-4xl with tailwind)
- font: use the default font
- font-weight: medium
- text color: white
- margin left right for centered div: 4px ( or mx-1 with tailwind)

Demo:
![Title](https://user-images.githubusercontent.com/78233689/229598229-afac474d-d717-4239-b5ad-1116ab7d0c4b.png)

White frame:
<img width="2064" alt="Untitled (1)" src="https://user-images.githubusercontent.com/78233689/229601452-41a43b32-003e-4b81-85b5-fcfa4b8fbf87.png">

**Comment by KalebArmbrust** [comment]
Hello, I would love to contribute to this project. Can you please assign me this issue?

**Comment by codecShivam** [comment]
I would like to work on  it. Could you please assign this issue to me?

**Comment by minhngo3818** [comment]
I think Kaleb came first, so I will assign him. Don't worry Shivam, I have assigned you in issue #130

**Comment by KalebArmbrust** [comment]
@minhngo3818 What page on the website should this be put on?

**Comment by minhngo3818** [comment]
All pages. If you want to test it, you can replace current Event title with the new Title component.

**Comment by KalebArmbrust** [comment]
@minhngo3818 I have the basic layout finished using tailwind, but can you please explain where I should be using the aspect ratio, and the ::before and ::after elements. Thanks! Here is what I have so far:
![Screenshot 2023-04-07 104255](https://user-images.githubusercontent.com/68127436/230637680-6bd32567-b546-4a28-bf5a-bd0b60acf3d7.png)
![Screenshot 2023-04-07 104308](https://user-images.githubusercontent.com/68127436/230637682-1e7c70b0-684b-4e4f-912d-2077784585a1.png)
![Screenshot 2023-04-07 104214](https://user-images.githubusercontent.com/68127436/230637683-1f4e4a70-6d6f-4c57-8bc2-b9176a176380.png)

**Comment by minhngo3818** [comment]
::before and ::after are for two lines that wrap around the title. Since you have a different approach to this, you don't include those and we can use your code. For the aspect ratio, the width of this component can be 2/3 or 3/4 of the screen. Since it depends on its parent, the width is always 100% of the parent's width.

**Comment by KalebArmbrust** [comment]
Okay, I am having a hard time with the aspect ratio. I have tried adding it to my component (using tailwind) but it doesn't seem to be changing anything. Also I have added my Title component to each functioning page with the respective colors and titles, deleting their place holders and commenting out the css styles that was used for those titles.

![Screenshot 2023-04-10 134152](https://user-images.githubusercontent.com/68127436/230970847-161f57e4-d09c-4a87-893f-a40fb57ad59f.png)
![Screenshot 2023-04-10 134159](https://user-images.githubusercontent.com/68127436/230970848-64db9d77-416b-4064-88ee-8092dbd777f2.png)
![Screenshot 2023-04-10 134210](https://user-images.githubusercontent.com/68127436/230970853-72ae1797-7cea-4cbc-aa8a-4f6e31172ff9.png)
![Screenshot 2023-04-10 134218](https://user-images.githubusercontent.com/68127436/230970856-7b2c6793-951c-4668-b84e-2a47a4130efc.png)

**Comment by minhngo3818** [comment]
Based on your pics, I think the title component is above the page component or maybe the wrapper inside the page component So it looks large. This should be under Can you show the code for the page component that you add the title to? or you can raise this PR, so I can review this further?

**Comment by KalebArmbrust** [comment]
@minhngo3818 Okay I wasn't sure if you wanted the component at the very top of the page or just before the other content. I will change this!

**Comment by KalebArmbrust** [comment]
@minhngo3818 I just submit a pull request for review, but it is not giving me the option to assign myself, a reviewer, or give labels.

**Comment by minhngo3818** [comment]
I approved your commits. Options should be open for you. Let me review your PR

**Comment by KalebArmbrust** [comment]
The settings icon isnt showing for me still.

![Screenshot 2023-04-13 123449](https://user-images.githubusercontent.com/68127436/231839470-3e5a1907-eeda-4b03-8933-94ed1ec2f33e.png)

**Comment by minhngo3818** [comment]
I added tags to your PR. Let me try to fix it.
