### ISSUE TITLE
Frontend - Restyle Resources Tab bar

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#131]
The resources tab bar must be restyled according to the UI design. Use ```Tailwind css``` to restyle

Tailwind doc: Tailwind doc: https://tailwindcss.com/docs/aspect-ratio

Directory: ```~/client/src/pages/resources/*```,  work in ```Resources.jsx``` and ```resources.css``` files

Styling detail:
- max-width: 2/3 full-screen width
- width: full
- height: 64px
- drop shadow
- can apply grid to create three columns
- text color: ```#ffffff```
- background-color: ```#2A2C2E```
- text color on hover: ```#2A2C2E```
- background on hover ```#ff9617```
- font-size: 24px (or tailwind default text-base no need to define)
- font-weight: bold
- transition: ease-in-out 300ms
- there is no gap between any two tabs

Demo:
![Tabs](https://user-images.githubusercontent.com/78233689/229680743-a07f2a2d-a71d-463a-894c-f1010e222cd2.png)

White frame:
<img width="3264" alt="Untitled" src="https://user-images.githubusercontent.com/78233689/229684115-62b6cfb9-8539-46e0-aa4a-1be43564c555.png">

**Comment by codebysid** [comment]
hey, i would love to contribute to this project, so could you please assign me this issue.
