### ISSUE TITLE
Frontend - Add Colors to Tailwind Config

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#135]
The current tailwind UI does not have a custom set of colors for our website. This task requires specifying color names in the `tailwind.config.js` file. So, once we change styling from `CSS` to `tailwind`, we will use color names instead of hex codes. This task is to prepare for converting `CSS` to `Tailwind`.

To add colors name: 
- Open `tailwind.config.js`
- Add a field named "colors" and map color name for each color hex code

<a href="https://tailwindcss.com/docs/customizing-colors">See Tailwind instructions</a>

Here is the set of colors to specify:
orange: `#FF9617`
orange-dim: `#D38830`
blue: `#2196F3`
smoke: `#EEEEEE`
smoke-dark: `#CCCCCC`
gray: `#212224`
gray-dark: `#1F1F21`
gray-med: `#2A2C2E`
gray-mild: `#3D3F43`
gray-light: `#494c50`

**Comment by dialejo24** [comment]
Hi there👋
could i work on this issue ?

**Comment by minhngo3818** [comment]
Sure

**Comment by dialejo24** [comment]
there's already a colors field in the file on [line 6] (https://github.com/Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io/blob/4803c90dba9ed83d46840d9df3463325e7524ca8/client/tailwind.config.js#L6). should i work on that object?

**Comment by minhngo3818** [comment]
yeah, you can add colors to that object. You don't have to create a new one.
