### ISSUE TITLE
Frontend - create Event Content component (wrapper)

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#139]
The current event content show information and images in a column. This task is to prepare for restyling the Event content component which displays information on the left and images on the right. ( The light gray section in the demo). Use CSS for this component.

To do this:
- under directory `~/client/src/components/events/event-expand/*`,  create `event-content.js` and `event-content.css` file
- create a react component called EventExpand
- see the current event expand component from file `~/client/src/pages/Events.js`  from line 67 for more info
- make sure to add prop types for this component. See <a href="https://www.npmjs.com/package/prop-types">link<a>

Props:
- isExpand: a boolean to indicate whether or not the event is expanding
- detail: string
- meetingUrl: string
- images: a list of string

Styling:
- background-color: `#3D3F43`
- border-radius: 10px
- display: flex
- max-height: 800px
- width: depend on the parent component
- Ignore padding and margin for this component since this task depends on #136 

Demo: (the entire event widget):

![Event 5](https://user-images.githubusercontent.com/78233689/230753121-deea64fb-6dc0-4c72-83f7-418d77f45971.png)

**Comment by prgmnn92** [comment]
please assign this task to me

**Comment by minhngo3818** [comment]
Sure

**Comment by minhngo3818** [comment]
solved #141
