### ISSUE TITLE
Frontend - Tutorial component and restyle

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#140]
Create a react component for the tutorial widget. This React component is expanded if the user clicks on it and shrank if clicked again. Descriptions and links are shown when the component is expanded. This task uses CSS for styling

Instructions:
- create react use State hook to handle expand/not-expand
- under the directory `~/client/src/components/resources/tutorials/*`, create a file named `tutorials.js` under that directory
- since all widget styles in resources depend on the same `pages/resources.css`, copy the file to `~/client/src/components/resources/*` and modify the CSS class
- make sure to add props type like the old component.
- see file `~/client/src/pages/resources/Tutorials.jsx` for reference

Props:
- id: number
- title: string
- description: string
- url: string
- tags: a list of string

Styling details:
- background-color: `#2A2C2E`
- display: flex
- padding: 20-36px ( as long as it's similar to the demo)
- drop shadow

- Title:
    - text color: white
    - font-size: 24px
    - make sure the text jumps into the next line if overflows (demo)
    - underline: 2px, color: `#ff9617`

- Content:
    - Text:
        - margin-top-bottom: 10px
        - width: full (max-width depends on the parent component)
        - text-color: white
        - font-size: 16px
    - URL:
        - text-color: `#ff9617`
        - font-size: 16px
- Tags:
    - Create a component that wraps all tags
    - For each tag, create a box that has 
        - margin - right: 10px
        - margin top-bottom: 5px
        - the text is center, 
        - font-size 16px, 
        - text: white
        - border: `#2196f3`, 1px
        - border-radius: 2px

Demo:

not expanded
![Tab Item 4](https://user-images.githubusercontent.com/78233689/230753866-83100fea-d397-485a-a77f-d2cb2ed53d95.png)

expanded
![Tab Item 5](https://user-images.githubusercontent.com/78233689/230753872-61c5fbab-99ea-4555-be64-b663faf24e0a.png)

White frame:
<img width="2960" alt="OCC CSC - White frames" src="https://user-images.githubusercontent.com/78233689/230754962-25944fdf-43e9-4d54-8244-688c667c1766.png">

**Comment by 777Prabhjot** [comment]
i would love to do this task can i
