### ISSUE TITLE
Pagination for Resources Tabs

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#28]
At the moment, each tab of resources page need pagination to show shorter version of the list. It will help user easily to view the content in each tab. The pagination will not show if there are less than 10 items

**Comment by KHVBui** [comment]
Is pagination really the solution to improving visibility and preventing the user from being overwhelmed? 

I figured that each tab would have sub-sections that could collapse too. 
Like for Readings, we could further divide into sub-sections of language, or by category of info (algorithms, data structures, cybersecurity, etc.)

**Comment by KHVBui** [comment]
If we're going to end up with a ton of resources, we could have those sub-sections be listed as sub-tabs underneath the big tabs so it stays tidy.

Kind of like this picture:
<img width="448" alt="Screen Shot 2022-07-26 at 6 32 21 PM" src="https://user-images.githubusercontent.com/36748732/181141074-d979f29c-7451-4994-899a-81869c548e5d.png">
.

**Comment by minhngo3818** [comment]
That's a good idea since we need something to filter the entire list to get items from a specific category. However, we still need pagination because it can limit amount of data to retrieve from backend. For example, if a sub-tab has a thousands of items, a sub-tab at 4th page will retrieve only 5 items from database with the pagination. On the other hand, it will retrieve thousands of item without pagination. Hence, pagination costs much less memory consumption.

**Comment by minhngo3818** [comment]
This task will use a pagination component for entire website, which require to complete issue #102
