### ISSUE TITLE
Homepage Banner

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#41]
The Homepage banner will be similar to photo below. Background for banner can be an image or a color. Make sure it well fit with the dark mode.  

Sample slogans : "we code like monkeys", "The club is what you make it to be" - Professor Jang

**Please use tailwind CSS for styling**

![minh01-designs](https://user-images.githubusercontent.com/78233689/182265999-075e2268-65ec-402a-bdb8-3020573934c6.png)

**Comment by KHVBui** [comment]
Hi @dylst, is this something you're still interested in working on?
