### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#46]
Club Website currently have 9 severe vulnerabilities. This can cause some cybersecurity issues.

![vulnerabilities](https://user-images.githubusercontent.com/78233689/183014923-a31c9e27-fd54-492f-bfb5-c8264504a36c.png)
"

**Comment by KHVBui** [comment]
Not even sure we can fix these without contributing and patching the dependencies' projects directly. I've had a case where npm audit or updating just broke other things.

The other option is to find other dependencies that can perform the same function without vulnerabilities or not those dependencies at all if possible.

**Comment by jameslindfors** [comment]
@minhngo3818 I believe this issue has been solved and can be closed.
