### ISSUE TITLE
Rebuild workflow for mock-up website & deploy on github page

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#57]
Currently the deployment workflow `page-build-deployment` failed to render demo since more implements has been adding to the project. We need to have the solution for that in order to show it. 

There two ways: 
Specify `client` (frontend) folder for deployment if possible, so we can keep the `main` branch for deployment. However, we may need to remove fake data in the frontend before actual deployment.

<s>Or, create `demo-version` branch to for hosting the demo. Any changes in frontend must be merged to `demo branch` before merging to `main`. This way we separate demo environment and actual environment</s>

**Comment by KHVBui** [comment]
The first way sounds like it might be best. I don't think we need to remove the fake data until the club is actually ready to put stuff in, since it's just for demo purposes.

A demo-version branch seems like it would give everyone unnecessary extra work.

**Comment by KHVBui** [comment]
Also, every time we do "npm run build" we create a static build for the site right now. Wouldn't the fastest thing right now be to move the "static" folder that it produces to the "public" folder to deploy?

**Comment by minhngo3818** [comment]
I agree the first way. It sounds more relevant and less issues. For `npm run build`, we will definitely use it to bundle up frontend. There're some requirements for github page so I'll add some packages to the update.

**Comment by minhngo3818** [comment]
Solved in #74
