### ISSUE TITLE
Events Expand Button not centered with certain tablets

### ISSUE THREAD

**Issue by KHVBui** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#59]
Surface Pro 7:
<img width="684" alt="Screen Shot 2022-08-17 at 7 45 47 PM" src="https://user-images.githubusercontent.com/36748732/185281757-06143262-78cb-4ce1-b659-b930fe7e9eb4.png">

iPad Air:
<img width="657" alt="Screen Shot 2022-08-17 at 7 38 09 PM" src="https://user-images.githubusercontent.com/36748732/185281761-ce9bbf63-e20b-40ee-8251-757103317167.png">

**Comment by minhngo3818** [comment]
This bug will be patched in pr #49
