### ISSUE TITLE
Data Model - Tutorials

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#65]
Create a data model for tutorials objects using mongoose Schema. Add few test cases in model test file.
Path: backend > models > tutorials

For mongoose Schema, please read documentation https://mongoosejs.com/docs/guide.html. Pay attention to Schema and Schema Types

For testing, recommend watch  https://www.youtube.com/watch?v=ACzMbQEq_tw from minute 10

Data properties:
- title
- description
- url
- array of Tag
- createdDate (used in admin page)
- updatedDate (used in admin page)

**Comment by justinpaulosolo** [comment]
I would like to get assigned this task.
