### ISSUE TITLE
API Routing - Tutorials - DELETE one or many tutorial instances

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#81]
This task require issue #65 to complete. DELETE method is in REST api that will delete instances of a data model by request from the frontend. The admin also want to delete some tutorials maybe because of it is outdated or the videos is removed from Youtube. 

There are two situations when using DELETE method. First, the admin want to delete only one instance of tutorials, Second the admin want to delete many instances, which is controllable. We don't consider delete-all because that will be the risk of loosing all data.  

Once again, use express js, mongoose, and mongodb to do this task. The working directories are `routes/tutorials/tutorials-route.js` for adding delete route, and `controller/tutorials/tutorials-controller.js` for adding routing logic.

**Comment by EdwinEstrada102** [comment]
Not completed, was playing around with the website.

**Comment by minhngo3818** [comment]
This issue is outdated. We're going to work with a general controller function which apply for multiple data models. Mentioned PR #115 . Please stay tuned!
