### ISSUE TITLE
Large Bundle Size Makes Website Slow

### ISSUE THREAD

**Issue by minhngo3818** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#86]
This is an issue when bundling up the frontend folder. In the attached picture, the bundle size is about 1MB which is much larger than recommended size.As a result, our website is slow. Obviously, the demo website performs a bit slow comparing to when running development mode. Switching pages and the animation in resources will show the issue.

There are some solutions for it. One of suggestion is lazy-load or code-splitting techniques, aka import when needed. Other solution is to use `vite` package to do lazy load with some awesome features (it runs like Flash).

See links below for more information:
React code splitting: https://reactjs.org/docs/code-splitting.html
Vite: https://vitejs.dev/guide/why.html

<img src="https://user-images.githubusercontent.com/78233689/190963674-4b385c7c-36ba-4f74-8226-08fc90ddef66.png" />

**Comment by jameslindfors** [comment]
+1 for vite

> A big contributor to the size and speed issues is the npm packages. [Here are the bundlephobia results](https://bundlephobia.com/scan-results?packages=@emotion/react@11.9.3,@emotion/styled@11.9.3,@faker-js/faker@7.3.0,@fortawesome/fontawesome-svg-core@6.1.1,@fortawesome/free-brands-svg-icons@6.2.0,@fortawesome/free-regular-svg-icons@6.1.1,@fortawesome/free-solid-svg-icons@6.1.1,@fortawesome/react-fontawesome@0.1.18,@mui/icons-material@5.8.4,@mui/material@5.8.5,@mui/styled-engine-sc@5.8.0,@testing-library/react@13.3.0,@testing-library/user-event@13.5.0,axios@0.27.2,bootstrap@5.1.3,bootstrap-icons@1.8.3,photoswipe@5.3.0,react@18.1.0,react-bootstrap@2.4.0,react-dom@18.1.0,react-photoswipe-gallery@2.2.1,react-router-dom@6.3.0,react-spinners@0.13.4,react-youtube@9.0.3,styled-components@5.3.5,web-vitals@2.1.4&sortMode=size). Some of these packages are already <500kb in size significantly adding to the overall bundle size.
 
Suggested options to reduce the size (in addition to code-splitting, etc.):
- Explore modifying webpack configurations
This would take some understanding of how webpack bundles and what optimization options are available. From what I've seen there is not a super straightforward way to modify the config without ejecting. Once ejected, a config folder is created with all webpack configuration files.
- Remove unused or excessively large packages
The largest package, fakerjs, won't be used in prod so this can either be swapped for hardcoded dummy data or a smaller package and that will reduce the size fairly easily. There are also many css and icon packages so some of those may be redundant. Selecting one icon library and css framework to use for the whole project could remove a bunch of extra dependencies.
- Move dependencies to dev-dependencies
Packages like @testing-library/react don't need to be a part of the production bundled dependencies so it can be moved to dev-dependencies. It's probably smart to reevaluate all packages and see what can be moved to dev deps.
- Migrate to vite
Requires ejecting from CRA and webpack. This also requires configuration for the build to minify the build.

I think it's worth it to make changes to the npm packages that are used in the project and then analyze if it's worth it to eject from react-scripts and modify the webpack configuration or to migrate to vite.

**Comment by minhngo3818** [comment]
I agree, we should try `vite` in our project. Hopefully, it will reduce significantly bundle size. 

Among dependencies, Mui seems to consume a lot of resources. Beside, it causes 9 vulnerabilities. So, there are less benefit to keep it. Some files must be modified by using different package or coding js components

We should choose the most various icon package

Test dependencies probably needs to move to dev-dependencies.   

Faker JS is temporarily used in frontend to show dummy. It has a value of generating large chunk of data. Since, we start working in backend, I think should used it in the backend for running test, or adding dummy data. I'm not sure if we can add it into dev-dependencies

**Comment by jameslindfors** [comment]
I did some testing and [migrated to vite.](/jameslindfors/Computer-Science-Club-OCC.github.io/tree/migrate-webpack-to-vite) I left all the original dependencies and added two vite npm packages. Already the resource size is 1MB smaller than with react-scripts. I did another test where I removed all the css frameworks, moved testing dependencies to dev, and swapped faker for dummy data and I was able to get the resource size to only 156KB. Small + fast bundles are definitely attainable. 

Note - I did have to change all `.js` files that contained a react component to `.jsx` for vite to build 

### Vite Resource Size  2.9.MB - Request Time 14ms
![vite-package_bundle](https://user-images.githubusercontent.com/63133254/192128625-bce8fa8a-3054-4ecc-b420-c52c58059cce.png)
### React-Scripts Resource Size 4.0MB - Request Time 30ms
![react-scripts_bundle](https://user-images.githubusercontent.com/63133254/192128626-9ec4a054-3cd4-4b62-88a8-87fa3df6b6f6.png)

**Comment by minhngo3818** [comment]
That's a pretty good result after migrating to `vite`. I'm certain that there is a corruption by removing css frameworks. As we're gonna have people work on our custom css, we probably need to remove most of css frameworks. 

I think we can replace icon packages with downloadable icons and use them in `<i>` tag. Ideally, that won't cost too much memory.
