### ISSUE TITLE
Bug: Dates on Events are too large for their boxes

### ISSUE THREAD

**Issue by KHVBui** [Computer-Science-Club-OCC/Computer-Science-Club-OCC.github.io#96]
Starting to implement Tailwind with app.css has broken elements that utilize the `<p>` tag. Tailwind overrides default margins that the styling for numerical dates or details used in the past.

![Screen Shot 2022-10-07 at 11 13 57 AM](https://user-images.githubusercontent.com/36748732/194623457-bc93aa09-90af-471e-aa12-5136e5a0e13e.png)
![Screen Shot 2022-10-07 at 11 19 59 AM](https://user-images.githubusercontent.com/36748732/194624111-eb7b0b0f-40e6-4723-aed8-d5dd192ff754.png)

**Comment by minhngo3818** [comment]
This bug will be solved in the upcoming tailwind migration task
